server:
  port: 8080
spring:
  datasource:
    password: Whatever@12345
    username: whatever
    url: jdbc:mysql://localhost:3306/soen6011?useSSL=false&allowPublicKeyRetrieval=true
   
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true 
  servlet:
    multipart:
      enabled: TRUE
     
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations=classpath: /static/